server:
  port: 8081
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10000MB
      max-request-size: 10000MB

upload:
  file-max-size: 5120000
  suffix-filter: .jpg.png
  download-url: /api/file/download
  file-path: C:\Users\win7\Downloads
  preview-image-url: /api/file/previewImage/

mvc:
  enabled: true
  static-path: classpath:/static/
  index: html/index.html

jdbc:
  enabled: true
  driver-class: com.mysql.cj.jdbc.Driver
  druid:
    enabled: true
    context-path: /druid/*
    username: admin
    password: admin
  init-sql:
    enabled: true
    file-name-prefix: V
    file-name-separator: __
    file-name-suffix: .sql
    table-name: init_sql_version
  master:
    enabled: true
    url: jdbc:mysql://128.0.1.3:3306/new-mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 123456
  db-list:
    admin:
      enabled: true
      url: jdbc:mysql://128.0.1.3:3306/new-mall-admin?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
      username: root
      password: 123456
      init-sql-locations: classpath:db/admin

mybatis:
  enabled: true
  type-aliases-package: matrix.project.mall.mapper
  mapper-locations: classpath*:mapper/**/*Mapper.xml

redis:
  enabled: true
  default-expire: 7200
  standalone:
    enabled: true
    host: 128.0.1.3
    port: 6379
    password: 123456
    database: 2

op-log:
  enabled: true
  db: admin

pay:
  enabled: false
  notify-domain: http://vwkit.com
  db: master
  alipay:
    enabled: false
    test: false
    app-id:
    sign-type:
    return-url: http://vwkit.com/returnUrl
    private-key:
    public-key:
  wepay:
    enabled: false
    app-id:
    mch-id:
    mch-key:
    key-path:
    secret:
    sub-app-id:
    sub-mch-id:
