CREATE TABLE admin_user
(
    USER_ID     VARCHAR(255) NOT NULL COMMENT '用户ID',
    USERNAME    VARCHAR(32)  NOT NULL COMMENT '用户名',
    PASSWORD    VARCHAR(255) NOT NULL COMMENT '密码',
    IS_DEFAULT  INT(1)       NOT NULL DEFAULT 0 COMMENT '默认ADMIN(不允许删除)',
    SHOP_ID     VARCHAR(255) COMMENT '店铺ID(为空时管理员账号)',
    CREATE_TIME DATETIME     NOT NULL COMMENT '创建时间',
    UPDATE_TIME DATETIME     NOT NULL COMMENT '更新时间',
    STATUS      INT(1)       NOT NULL COMMENT '状态(1:启用,0:禁用,-1:删除)',
    PRIMARY KEY (USER_ID)
);
INSERT INTO admin_user (USER_ID, USERNAME, PASSWORD, IS_DEFAULT, SHOP_ID, CREATE_TIME, UPDATE_TIME, STATUS)
VALUES ('1', 'admin', 'E10ADC3949BA59ABBE56E057F20F883E', '1', NULL, NOW(), NOW(), 1);
INSERT INTO admin_user (USER_ID, USERNAME, PASSWORD, IS_DEFAULT, SHOP_ID, CREATE_TIME, UPDATE_TIME, STATUS)
VALUES ('2', 'shop1', 'E10ADC3949BA59ABBE56E057F20F883E', '0', '1', NOW(), NOW(), 1);