CREATE TABLE shop (
  SHOP_ID VARCHAR(255) NOT NULL COMMENT '店铺ID',
  SHOP_NAME VARCHAR(255) NOT NULL COMMENT '店铺名称',
  SHOP_LOGO VARCHAR(255) COMMENT '店铺logo',
  SHOP_DESC TEXT COMMENT '店铺描述',
  SHOP_STAR INT(1) NOT NULL DEFAULT 5 COMMENT '店铺星级(最高5星)',
  CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
  UPDATE_TIME DATETIME NOT NULL COMMENT '更新时间',
  STATUS INT(1) NOT NULL COMMENT '状态(1:启用,0:禁用,-1:删除)',
  PRIMARY KEY (SHOP_ID)
);
INSERT INTO shop (SHOP_ID, SHOP_NAME, SHOP_LOGO, SHOP_DESC, CREATE_TIME, UPDATE_TIME, STATUS)
VALUES (1, '自营店铺', '', '', NOW(), NOW(), 1);

CREATE TABLE brand (
    BRAND_ID VARCHAR(255) NOT NULL COMMENT '品牌ID',
    BRAND_NAME VARCHAR(255) NOT NULL COMMENT '品牌名称',
    BRAND_URL VARCHAR(255) COMMENT '品牌链接',
    BRAND_LOGO VARCHAR(255) COMMENT '品牌Logo',
    SHOP_ID VARCHAR(255) NOT NULL COMMENT '店铺ID',
    CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
    UPDATE_TIME DATETIME NOT NULL COMMENT '更新时间',
    STATUS INT(1) NOT NULL COMMENT '状态(1:启用,0:禁用,-1:删除)',
    PRIMARY KEY (BRAND_ID)
);
INSERT INTO brand (BRAND_ID, BRAND_NAME, BRAND_URL, BRAND_LOGO, SHOP_ID, CREATE_TIME, UPDATE_TIME, STATUS)
VALUES (1, '小米', 'http://www.mi.com', 'https://s02.mifile.cn/assets/static/image/mi-logo.png', '1', NOW(), NOW(), '1');

CREATE TABLE category (
   CATEGORY_ID VARCHAR(255) NOT NULL COMMENT '分类ID',
   CATEGORY_NAME VARCHAR(255) NOT NULL COMMENT '分类名称',
   PARENT_ID VARCHAR(255) NOT NULL COMMENT '分类父级ID',
   SHOP_ID VARCHAR(255) NOT NULL COMMENT '店铺ID',
   CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
   UPDATE_TIME DATETIME NOT NULL COMMENT '更新时间',
   STATUS INT(1) NOT NULL COMMENT '状态(1:启用,0:禁用,-1:删除)',
   PRIMARY KEY (CATEGORY_ID)
);
INSERT INTO category (CATEGORY_ID, CATEGORY_NAME, PARENT_ID, SHOP_ID, CREATE_TIME, UPDATE_TIME, STATUS)
VALUES (1, '手机', '0', '1', NOW(), NOW(), '1');
