CREATE TABLE clients (
    CLIENT_ID VARCHAR(255) NOT NULL COMMENT '客户端ID',
    CLIENT_SECRET VARCHAR(32) NOT NULL COMMENT '客户端密钥',
    CLIENT_TYPE VARCHAR(10) NOT NULL COMMENT '客户端类型',
    PRIMARY KEY (CLIENT_ID)
);
INSERT INTO clients (CLIENT_ID, CLIENT_SECRET, CLIENT_TYPE) VALUES ('app', 'app475422484', 'APP');