CREATE TABLE client (
    CLIENT_ID VARCHAR(255) NOT NULL COMMENT '客户端ID',
    CLIENT_SECRET VARCHAR(32) NOT NULL COMMENT '客户端密钥',
    CLIENT_TYPE VARCHAR(10) NOT NULL COMMENT '客户端类型',
    PRIMARY KEY (CLIENT_ID)
);
INSERT INTO client (CLIENT_ID, CLIENT_SECRET, CLIENT_TYPE) VALUES ('app', 'app475422484', 'APP');
CREATE TABLE user (
  USER_ID VARCHAR(255) NOT NULL COMMENT '用户ID',
  USERNAME VARCHAR(32) NOT NULL UNIQUE COMMENT '用户名',
  NICKNAME VARCHAR(255) NOT NULL COMMENT '昵称',
  MOBILE VARCHAR(32) NOT NULL UNIQUE COMMENT '手机号',
  PASSWORD VARCHAR(32) NOT NULL COMMENT '密码',
  CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
  UPDATE_TIME DATETIME NOT NULL COMMENT '更新时间',
  STATUS INT(1) NOT NULL COMMENT '状态(1:启用,0:禁用,-1:删除)',
  PRIMARY KEY (USER_ID)
);
INSERT INTO user (USER_ID, USERNAME, NICKNAME, MOBILE, PASSWORD, CREATE_TIME, UPDATE_TIME, STATUS)
VALUES ('1', 'test', '测试用户', '18888888888', 'E10ADC3949BA59ABBE56E057F20F883E', NOW(), NOW(), 1);