server:
  port: 8080
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10000MB
      max-request-size: 10000MB

jdbc:
  enabled: true
  driver-class: com.mysql.cj.jdbc.Driver
  master:
    enabled: true
    url: jdbc:mysql://128.0.1.3:3306/new-mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 123456

mybatis:
  enabled: true
  type-aliases-package: matrix.project.mall.mapper
  mapper-locations: classpath*:mapper/**/*Mapper.xml

redis:
  enabled: true
  default-expire: 7200
  standalone:
    enabled: true
    host: 128.0.1.3
    port: 6379
    password: 123456
    database: 1

op-log:
  enabled: true
  db: master

pay:
  enabled: false
  notify-domain: http://vwkit.com
  db: master
  alipay:
    enabled: false
    test: false
    app-id:
    sign-type:
    return-url: http://vwkit.com/returnUrl
    private-key:
    public-key:
  wepay:
    enabled: false
    app-id:
    mch-id:
    mch-key:
    key-path:
    secret:
    sub-app-id:
    sub-mch-id:
